### ISSUE TITLE
reference to JSE?

### ISSUE THREAD

**Issue by ShanEllis** [DataScienceInPractice/Site#3]
Is it worth including a reference to JSE paper (this could happen during review?) I'd envision this would happen during brief discussion of the course.

**Comment by TomDonoghue** [comment]
I can add JSE in! I guess I wasn't sure about the placeholder ref - the lack of DOI will fail the automatic reference check (which itself is not a big deal), but I have it in my mind that JSE comes out for real in November (is that right?) in which case, we might not get a real ref to add to JOSE before it would otherwise be done...?

**Comment by TomDonoghue** [comment]
JSE paper has now been referenced in the JOSE paper!
