### ISSUE TITLE
Phantom Python Introduction

### ISSUE THREAD

**Issue by krother** [DataScienceInPractice/Site#5]
When I click on **pandas** https://datascienceinpractice.github.io/assignments/D2_Pandas.html  there is no "Introduction to Python" in **Assignments** in the table of contents on the left.

When I click on **Data Analysis** https://datascienceinpractice.github.io/assignments/D5_DataAnalysis.html  it suddenly appears.

This issue was raised as part of the JOSE review https://github.com/openjournals/jose-reviews/issues/121

**Comment by TomDonoghue** [comment]
hey @krother - thanks for the note on this - I was able to replicate that on the previous deployment, there was some kind of quirk with the table of contents for the assignments, and in particular that `Python Introduction` would often disappear. 

I have updated Jupyter-book, and redeployed, and no longer see this issue. It seems to be fixed with the re-deployment, so I'm going to close this issue - but please re-open if it doesn't seem to be fixed for you!
